# Generated by Django 3.0.5 on 2021-05-01 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LANGUAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('java', 'Java'), ('c', 'C'), ('py', 'Python')], max_length=4)),
                ('image_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('volume_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
