# Generated by Django 3.0.5 on 2021-05-01 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='image_id',
            field=models.CharField(default='codercom/code-server', max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(default='py', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
