# Generated by Django 3.0.5 on 2021-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210501_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='Python', max_length=255),
        ),
    ]
